## Argo Configs
configs:
  params:
  # -- Run server without TLS
    server.insecure: true
server:
  extensions:
    # -- Enable support for Argo UI extensions
    enabled: true
# ~~~~ ここから下を追記or更新 ~~~~
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar
